# Generated by Django 5.2.17 on 2026-08-14 05:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('Movie', 'Movie'), ('TV', 'TV Show')], default='Movie', max_length=10)),
                ('status', models.CharField(choices=[('Unwatched', 'To Watch'), ('Watched', 'Watched')], default='Unwatched', max_length=15)),
                ('rating', models.IntegerField(default=0, help_text='Rating from 1 to 5 stars, 0 indicates unrated', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('genre', models.CharField(blank=True, default='', max_length=100)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, default='', max_length=1000)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media Item',
                'verbose_name_plural': 'Media Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
